### Tester la route d'inscription (POST /register)
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123",
    "first_name": "John",
    "last_name": "Doe",
    "phone": "0123456789",
    "siren": "123456789"
}


###

### Connexion d'un utilisateur existant
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123"
}

### Obtenir les informations de l'utilisateur connecté
GET http://localhost:3000/api/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTcyNzA0ODg5NywiZXhwIjoxNzI3MDUyNDk3fQ.JOThemZ9r6XgshOnwiM20Iqb_mwmSBS5ArlqIDS1VIs